# Server Port Configuration
server.port=8080

# BFHL User Details (Centralized and Configurable)
user.fullname=rishika_barua
user.dob=26052026
user.email=rishikabarua230031@acropolis.in
user.rollnumber=0827CS231216
